import { useCallback, useEffect, useRef, useState } from "react";
import { plotloomApi } from "../api";
import { Button, ErrorNotice } from "../components";
import type { ScriptReviewState } from "../types";

type Session = { projectId: string; epoch: number };

/** The F4 owner exposes upstream JSON directly and edits one bound section at a time. */
export function ScriptPanel({ projectId, readOnly }: { projectId: string; readOnly: boolean }) {
  const [state, setState] = useState<ScriptReviewState>(); const [assignment, setAssignment] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [sectionId, setSectionId] = useState(""); const [draft, setDraft] = useState("");
  const active = useRef<Session>({ projectId, epoch: 0 }); if (active.current.projectId !== projectId) active.current = { projectId, epoch: active.current.epoch + 1 };
  const owns = (session: Session) => active.current === session;
  const load = useCallback(async (session = active.current) => { try { const next = await plotloomApi.getScript(session.projectId); if (owns(session)) setState(next); } catch (reason) { if (owns(session)) setError(reason instanceof Error ? reason.message : "Unable to load script."); } }, [projectId]);
  useEffect(() => { const session = active.current; setState(undefined); setAssignment(""); setError(""); setBusy(false); void load(session); return () => { if (owns(session)) active.current = { projectId: session.projectId, epoch: session.epoch + 1 }; }; }, [projectId, load]);
  const act = (operation: () => Promise<unknown>, success?: () => void) => { const session = active.current; setBusy(true); setError(""); void operation().then(async () => { if (owns(session)) { success?.(); await load(session); } }).catch(reason => { if (owns(session)) setError(reason instanceof Error ? reason.message : "Script operation failed."); }).finally(() => { if (owns(session)) setBusy(false); }); };
  if (!state) return null;
  const candidate = state.candidate; const accepted = state.acceptedScript; const script = candidate?.status === "ready" ? candidate.script : accepted?.script; const bindings = Array.isArray(script?.sectionBindings) ? script.sectionBindings as Array<Record<string, unknown>> : [];
  const chooseSection = (id: string) => { setSectionId(id); const ep = bindings.find(item => item.sectionId === id)?.episode; const episode = Array.isArray(script?.episodes) ? script.episodes.find(item => typeof item === "object" && item !== null && (item as Record<string, unknown>).ep === ep) : undefined; setDraft(JSON.stringify(episode || {}, null, 2)); };
  const heading = state.status === "stale" ? "上下文已过期" : accepted ? `已接受 r${accepted.revision}` : candidate?.status === "ready" ? "可审核" : candidate?.status === "prepared" ? "等待 specialist" : "尚无剧本候选";
  return <article className="panel cast-panel" data-testid="script-review"><header><span>07 · F4 novel-script proposal</span><strong>{heading}</strong></header><p>完整 pilot 的三个稳定章节各绑定一个上游 episode。script.json 仍是创作权威；此处只保存最薄的 sectionBindings。F5 消费这条缝，旧 scene/beat authoring 的替换边界止于此。</p><div className="notice warning">这是非 episode pilot：上游 hook/cliff 与 duration 检查仅验证结构，不构成产品 gate 或节奏/悬念通过。每个章节须在 JSON 中如实标明其进入或终局状态。</div>{state.staleReasons.length > 0 && <div className="notice warning">{state.staleReasons.join("；")}</div>}
    {!candidate && state.status !== "reopened" && <Button variant="primary" disabled={readOnly || busy} onClick={() => { const session = active.current; setBusy(true); void plotloomApi.prepareScriptCandidate(session.projectId).then(result => { if (owns(session)) { setAssignment(result.assignment); return load(session); } }).catch(reason => { if (owns(session)) setError(reason.message); }).finally(() => { if (owns(session)) setBusy(false); }); }}>准备并复制 script specialist handoff</Button>}
    {candidate?.status === "prepared" && <><Button disabled={readOnly || busy} onClick={() => { const session = active.current; setBusy(true); void plotloomApi.recoverScriptHandoff(session.projectId, candidate.jobId).then(async result => { if (owns(session)) { setAssignment(result.assignment); await load(session); } }).catch(reason => { if (owns(session)) setError(reason instanceof Error ? reason.message : "Unable to recover script handoff."); }).finally(() => { if (owns(session)) setBusy(false); }); }}>重新复制冻结 handoff</Button><Button disabled={readOnly || busy} onClick={() => act(() => plotloomApi.refreshScriptCandidate(projectId, candidate.jobId))}>刷新 specialist delivery</Button><Button variant="danger" disabled={readOnly || busy} onClick={() => act(() => plotloomApi.cancelScriptCandidate(projectId, candidate.jobId))}>取消 handoff</Button></>}
    {candidate?.status === "ready" && <><details open><summary>查看上游 script.json</summary><pre>{JSON.stringify(candidate.script, null, 2)}</pre></details>{candidate.reportAvailable && <Report projectId={projectId} jobId={candidate.jobId} />}<Button variant="primary" disabled={readOnly || busy} onClick={() => act(() => plotloomApi.acceptScriptCandidate(projectId, { jobId: candidate.jobId, expectedScriptRevision: candidate.expectedScriptRevision, binding: candidate.binding, script: candidate.script || {} }))}>显式接受完整 pilot 剧本</Button><Button variant="danger" disabled={readOnly || busy} onClick={() => act(() => plotloomApi.cancelScriptCandidate(projectId, candidate.jobId))}>拒绝并取消此剧本</Button></>}
    {accepted && <><small>已接受 hash {accepted.contentHash.slice(0, 12)}；任何章节修改都以稳定 section ID 定位，并保留其他已接受章节。</small>{state.status !== "reopened" && <Button variant="quiet" disabled={readOnly || busy} onClick={() => act(() => plotloomApi.reopenScript(projectId, accepted.revision))}>重新打开剧本</Button>}{state.status === "reopened" && <section><label>编辑章节<select disabled={readOnly || busy} value={sectionId} onChange={event => chooseSection(event.target.value)}><option value="">选择稳定章节</option>{bindings.map(item => <option key={String(item.sectionId)} value={String(item.sectionId)}>{String(item.sectionId)} · episode {String(item.episode)}</option>)}</select></label>{sectionId && <><textarea className="source-outline-json" disabled={readOnly || busy} rows={22} value={draft} onChange={event => setDraft(event.target.value)} /><Button variant="primary" disabled={readOnly || busy} onClick={() => { try { const episode = JSON.parse(draft) as Record<string, unknown>; act(() => plotloomApi.saveScriptSection(projectId, { expectedScriptRevision: accepted.revision, binding: accepted.binding, sectionId, episode })); } catch { setError("章节必须是有效 JSON。"); } }}>保存此章节，不覆盖其他章节</Button></>}</section>}</>}
    {assignment && <label>复制给 specialist 的冻结任务<textarea readOnly value={assignment} rows={5} /></label>}{error && <ErrorNotice message={error} />}</article>;
}

function Report({ projectId, jobId }: { projectId: string; jobId: string }) { return <details><summary>打开只读上游报告</summary><iframe title="derived upstream script report" className="source-outline-report" sandbox="" src={plotloomApi.scriptCandidateReportUrl(projectId, jobId)} /></details>; }
