"""Pin a supported Plotloom image-specialist checkout before ImageGen runs.

The delivery directory is untrusted, but this preflight makes the operating
boundary explicit: a specialist records the exact checkout and repository skill
before generation, and Refresh rejects a completion whose provenance differs.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import subprocess
from pathlib import Path


SUPPORTED_EXECUTION_CONTRACT = "codex_specialist.v2"
SUPPORTED_PREFLIGHT_VERSION = "p1.5-pin.v1"
SUPPORTED_SKILL_VERSION = "plotloom-image-specialist.v3"
SKILL_PATH = Path(".agents/skills/plotloom-image-specialist/SKILL.md")
_BYTECODE_CACHE_NAME = re.compile(
    r"[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z0-9_-]+(?:\.opt-[0-9]+)?\.pyc\Z"
)
PINNED_SOURCES = (
    SKILL_PATH,
    Path("scripts/cleanup_imagegen_staging.py"),
    Path("scripts/pin_image_specialist.py"),
    # API and persistence used to be monolith modules.  They are now package
    # owners, so pin their implementations recursively rather than pretending
    # their package façades attest the route and delivery code beneath them.
    Path("src/plotloom/api"),
    Path("src/plotloom/image_job_exchange.py"),
    Path("src/plotloom/image_job_contracts.py"),
    Path("src/plotloom/persistence"),
)


def canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _private_directory(path: Path, *, label: str) -> None:
    """Create the specialist's mutable transaction directories as private."""

    path.mkdir(mode=0o700, parents=True, exist_ok=True)
    details = path.lstat()
    if (
        path.is_symlink()
        or not stat.S_ISDIR(details.st_mode)
        or details.st_uid != os.geteuid()
        or stat.S_IMODE(details.st_mode) & (stat.S_IRWXG | stat.S_IRWXO)
        or (stat.S_IMODE(details.st_mode) & stat.S_IRWXU) != stat.S_IRWXU
    ):
        raise SystemExit(f"Unsupported delivery: {label} must be a private current-user directory.")


def _command(repository: Path, *args: str) -> bytes:
    return subprocess.check_output(["git", "-C", str(repository), *args])


def _safe_path(path: bytes) -> str:
    """Quote repository output so a hostile filename cannot alter diagnostics."""

    return json.dumps(os.fsdecode(path), ensure_ascii=True)


def _pinned_files_at_revision(repository: Path, revision: str, source: Path) -> tuple[bytes, ...]:
    files = tuple(
        item
        for item in _command(
            repository,
            "ls-tree",
            "-r",
            "-z",
            "--name-only",
            revision,
            "--",
            source.as_posix(),
        ).split(b"\0")
        if item
    )
    if not files:
        raise SystemExit(
            f"Unsupported checkout: pinned specialist source is not committed at HEAD: {_safe_path(os.fsencode(source.as_posix()))}."
        )
    return files


def _first_untrusted_bytecode_cache_path(cache_directory: Path) -> Path | None:
    """Return a cache entry that cannot be classified as generated bytecode.

    Git deliberately collapses an ignored ``__pycache__`` directory in porcelain
    output.  Expand only that ordinary runtime directory so source hidden below
    it cannot inherit the bytecode exception.  A valid entry is a non-executable
    regular PEP 3147-style ``.pyc``. Bytecode is runtime data even when its
    source module has since moved during a committed modularization.
    """

    try:
        directory_details = cache_directory.lstat()
        with os.scandir(cache_directory) as directory:
            entries = tuple(directory)
    except OSError:
        return cache_directory
    if cache_directory.is_symlink() or not stat.S_ISDIR(directory_details.st_mode):
        return cache_directory

    for entry in entries:
        entry_path = Path(entry.path)
        try:
            details = entry.stat(follow_symlinks=False)
        except OSError:
            return entry_path
        if (
            not stat.S_ISREG(details.st_mode)
            or stat.S_IMODE(details.st_mode) & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            or _BYTECODE_CACHE_NAME.fullmatch(entry.name) is None
        ):
            return entry_path
    return None


def _ignored_bytecode_cache_directory(repository: Path, path: bytes) -> Path | None:
    """Return the ignored cache directory represented by a porcelain path."""

    candidate = repository / os.fsdecode(path)
    if candidate.name == "__pycache__":
        return candidate
    if candidate.parent.name == "__pycache__":
        return candidate.parent
    return None


def _first_dirty_pinned_path(
    repository: Path, sources: tuple[Path, ...]
) -> bytes | None:
    """Return a changed tracked or untracked path under the pin boundary.

    ``git diff`` does not report untracked files, and an index-only diff misses
    some working-tree states.  Porcelain v1 with NUL separators covers staged,
    unstaged, deleted, untracked, and ignored entries without parsing
    shell-quoted paths.  Ignored entries matter here too: an ignored executable
    module below a package boundary must not evade a HEAD-only attestation.
    """

    output = _command(
        repository,
        "status",
        "--porcelain=v1",
        "-z",
        "--untracked-files=all",
        "--ignored=matching",
        "--",
        *(source.as_posix() for source in sources),
    )
    entries = iter(item for item in output.split(b"\0") if item)
    for entry in entries:
        # Ordinary porcelain records are ``XY SP path``.  A rename/copy has a
        # second NUL-delimited origin path, which we consume before returning
        # the changed destination path.
        if len(entry) < 4:
            continue
        status, path = entry[:2], entry[3:]
        if b"R" in status or b"C" in status:
            next(entries, None)
        if status == b"!!":
            cache_directory = _ignored_bytecode_cache_directory(repository, path)
            if cache_directory is not None:
                unsafe_path = _first_untrusted_bytecode_cache_path(cache_directory)
                if unsafe_path is None:
                    continue
                try:
                    return os.fsencode(unsafe_path.relative_to(repository).as_posix())
                except ValueError:
                    return path
        return path
    return None


def _verify_pinned_sources(repository: Path, revision: str) -> None:
    for source in PINNED_SOURCES:
        _pinned_files_at_revision(repository, revision, source)
    dirty_path = _first_dirty_pinned_path(repository, PINNED_SOURCES)
    if dirty_path is not None:
        raise SystemExit(
            f"Unsupported checkout: pinned specialist source has uncommitted changes: {_safe_path(dirty_path)}."
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Pin a supported Plotloom image-specialist package before generation.")
    parser.add_argument("--package", required=True, type=Path)
    args = parser.parse_args()
    package = args.package.resolve()
    request_path = package / "request.json"
    request = json.loads(request_path.read_text(encoding="utf-8"))
    preflight = request.get("specialistPreflight")
    if not isinstance(preflight, dict):
        raise SystemExit("Unsupported package: missing specialistPreflight.")
    if request.get("schemaVersion") != 3 or request.get("packageVersion") != 4:
        raise SystemExit("Unsupported package: expected schema version 3 and package version 4.")
    if preflight.get("version") != SUPPORTED_PREFLIGHT_VERSION or preflight.get("skillVersion") != SUPPORTED_SKILL_VERSION:
        raise SystemExit("Unsupported specialist preflight version or skill version.")
    if request.get("executionContract") != SUPPORTED_EXECUTION_CONTRACT or preflight.get("executionContract") != SUPPORTED_EXECUTION_CONTRACT:
        raise SystemExit(f"Unsupported execution contract: {request.get('executionContract')!r}.")
    skill_version = preflight.get("skillVersion")
    if skill_version != SUPPORTED_SKILL_VERSION:
        raise SystemExit("Unsupported package: unsupported specialist skill version.")
    repository = Path(__file__).resolve().parents[1]
    skill = repository / SKILL_PATH
    if not skill.is_file():
        raise SystemExit("Unsupported checkout: Plotloom image-specialist skill is missing.")
    revision = _command(repository, "rev-parse", "HEAD").decode().strip()
    _verify_pinned_sources(repository, revision)
    pin = {
        "jobId": request["jobId"],
        "requestHash": request["requestHash"],
        "executionContract": SUPPORTED_EXECUTION_CONTRACT,
        "skillVersion": skill_version,
        "codeRevision": revision,
        "skillHash": hashlib.sha256(skill.read_bytes()).hexdigest(),
    }
    delivery = package.parent / "delivery"
    _private_directory(delivery, label="delivery")
    _private_directory(delivery / "outputs", label="delivery outputs")
    target = delivery / "executor-pin.json"
    try:
        with target.open("x", encoding="utf-8") as output:
            output.write(canonical_json(pin))
    except FileExistsError as error:
        raise SystemExit("Executor pin already exists; do not overwrite or re-pin a prepared delivery.") from error
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
