import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "./fixture";
import { createScriptProject, fixture, hash, json, writeDelivery } from "./f5a-fixture";

test("pinned Art static reading preserves prompts, images and native disclosures", async ({ page, request, workbench }) => {
  const id = await createScriptProject(request, workbench.apiOrigin, "static-art-report", {}, ["cast"]);
  const root = `${workbench.apiOrigin}/api/v2/projects/${id}/art`;
  const art = await fixture("art.json");
  const prepared = await json(request.post(`${root}/candidates`, { data: { renderStyle: art.style } }));
  const reportArt = structuredClone(art);
  reportArt.scenes[0].sheetImage = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNn0AAAAASUVORK5CYII=";
  const sourcePath = path.join(path.dirname(prepared.deliveryPath), "art-report-source.json");
  await writeFile(sourcePath, JSON.stringify(reportArt));
  const report = execFileSync(process.execPath, ["third_party/shuohao-skills/skills/novel-art/scripts/novel-art.mjs", "render", sourcePath, "--html", "--lang", "en"], { cwd: path.resolve("..") });
  await writeDelivery(prepared, "art", art, report);
  await json(request.post(`${root}/candidates/${prepared.jobId}/refresh`));
  await json(request.post(`${root}/accept`, { data: { jobId: prepared.jobId, expectedArtRevision: 0, binding: prepared.binding } }));
  const archiveUrl = `${root}/candidates/${prepared.jobId}/report`;
  expect(await (await request.get(archiveUrl)).text()).toBe(report.toString());
  const projected = await request.get(`${archiveUrl}?presentation=static`);
  expect(projected.headers()["content-security-policy"]).toBe("sandbox; default-src 'none'; style-src 'unsafe-inline'; img-src data:;");
  await page.setViewportSize({ width: 1280, height: 768 });
  await page.goto(`${workbench.frontendOrigin}/v2/?project=${id}&stage=source#art`);
  const frame = page.frameLocator('iframe[title="美术设定报告静态预览"]');
  await expect(frame.locator("details.pr").first()).toHaveAttribute("open", "");
  const prompt = frame.locator("details.pr").first();
  await expect(prompt.locator("p")).toBeVisible();
  await prompt.locator("summary").click();
  await expect(prompt).not.toHaveAttribute("open");
  await prompt.locator("summary").click();
  await expect(prompt.locator("p")).toBeVisible();
  for (const selector of [".copy", ".expo"]) for (const control of await frame.locator(selector).all()) await expect(control).toBeHidden();
  await expect(frame.locator("button.zoom")).toBeDisabled();
  await expect(frame.locator("button.zoom img")).toBeVisible();
  expect(await frame.locator("button.zoom img").getAttribute("src")).toBe(reportArt.scenes[0].sheetImage);
  const opener = page.getByRole("button", { name: "放大阅读报告", exact: true });
  await opener.click();
  const dialog = page.getByRole("dialog", { name: "美术设定报告（静态阅读）", exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.locator("iframe")).toHaveAttribute("sandbox", "");
  await dialog.getByRole("button", { name: "关闭报告", exact: true }).click();
  await expect(opener).toBeFocused();
  await opener.click(); await page.keyboard.press("Escape");
  await expect(dialog).toBeHidden(); await expect(opener).toBeFocused();
  expect(await (await request.get(archiveUrl)).text()).toBe(report.toString());
  expect(hash(await readFile(path.join(prepared.deliveryPath, "report.html")))).toBe(hash(report));
});
