import { execFileSync } from "node:child_process";
import path from "node:path";
import { expect, test } from "./fixture";
import { json } from "./f5a-fixture";

test.use({ actionTimeout: 10_000 });

test("creator Production shows every repeated scene and exact cut, guards drafts and preserves installed media", async ({ page, request, workbench }, info) => {
  test.setTimeout(120_000);
  const id = execFileSync("uv", ["run", "python", "-m", "frontend.e2e.fixtures.bridge_handoff_project", "--outputs", workbench.outputsRoot, "--application", workbench.applicationDataRoot, "--seconds", "2.5", "--repeat-scenes"], { cwd: path.resolve(".."), encoding: "utf8" }).trim();
  const root = `${workbench.apiOrigin}/api/v2/projects/${id}`;
  const retained = await json(request.get(`${root}/stages`));
  const bridge = await json(request.get(`${root}/production-bridge`));
  const controlId = (await json(request.get(`${root}/script`))).acceptedScript.binding.routeOnlySectionIds[0];
  const secondScene = bridge.proposal.scenes.find((scene: { sectionId: string; sceneIndex: number }) => scene.sectionId === "opening" && scene.sceneIndex === 2);
  const exact = bridge.proposal.cuts.filter((cut: { sectionId: string; sceneIndex: number }) => cut.sectionId === "opening" && cut.sceneIndex === 2).at(-1);
  const writes: string[] = [], errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => { if (request.url().includes("/api/v2/") && request.method() !== "GET") writes.push(request.url()); });
  await page.setViewportSize({ width: 1700, height: 900 });
  await page.goto(`${workbench.frontendOrigin}/v2/?project=${id}&stage=creator`);
  await page.getByRole("tab", { name: "制作", exact: true }).click();
  const production = page.getByTestId("creator-production");
  await expect(production.locator("[data-production-scene]")).toHaveCount(2);
  await expect(production.locator("[data-production-shot]")).toHaveCount(9);
  await expect(production.locator(`[data-production-scene="${secondScene.sceneId}"]`)).toContainText("场次 2 · S01 · 5 个镜头");
  await expect(page.getByRole("button", { name: "应用到故事路线", exact: true })).toBeDisabled();
  await expect(page.locator(".creator-inspector > footer")).toContainText("不能重新安装剧情图");
  await page.screenshot({ path: info.outputPath("production-1700-viewport.png") });
  await page.locator(`[data-creator-node="${controlId}"] .creator-node-select`).click();
  await expect(production).toContainText("没有剧本场次、镜头或节点视频");
  await expect(production.locator("[data-production-shot]")).toHaveCount(0);
  await page.locator('[data-creator-node="opening"] .creator-node-select').click();
  const shot = production.locator(`[data-production-shot="${exact.shotId}"]`);
  await expect(shot.getByRole("button", { name: "镜头审核与媒体", exact: true })).toBeEnabled();
  await shot.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("second-scene-exact-shot-viewport.png") });
  await shot.getByRole("button", { name: "镜头审核与媒体", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`stage=storyboard&entity=shot%3A${exact.shotId}`));
  const summary = page.getByTestId("shot-preparation-summary");
  await expect(summary).toContainText(`当前镜头准备状态 · ${exact.shotId}`);
  await expect(summary).toContainText("精确来源时长 2.5 秒 · 当前绑定");
  await expect(summary).toContainText("缺少当前批准");
  expect(writes).toEqual([]);
  await page.getByRole("button", { name: "创作工作台", exact: true }).click();
  const title = page.getByLabel("章节标题", { exact: true }), original = await title.inputValue();
  await title.fill(`${original} · local unsaved meaning`);
  await page.getByRole("tab", { name: "制作", exact: true }).click();
  await expect(production).toContainText("图草稿与当前已应用路线不同");
  await expect(production.locator(`[data-production-shot="${exact.shotId}"]`).getByRole("button", { name: "镜头审核与媒体", exact: true })).toBeDisabled();
  expect(await json(request.get(`${root}/stages`))).toEqual(retained);
  expect(await json(request.get(`${root}/production-bridge`))).toEqual(bridge);
  await page.getByRole("tab", { name: "故事", exact: true }).click();
  await title.fill(original);
  await page.getByRole("tab", { name: "制作", exact: true }).click();
  await expect(production.locator(`[data-production-shot="${exact.shotId}"]`).getByRole("button", { name: "镜头审核与媒体", exact: true })).toBeEnabled();
  await page.locator(`[data-creator-node="${controlId}"] .creator-node-select`).click();
  await page.getByRole("tab", { name: "故事", exact: true }).click();
  await page.getByLabel("包含画面与剧本场景").check();
  await expect(page.getByRole("button", { name: "确认图内容", exact: true })).toBeDisabled();
  await page.getByLabel("包含画面与剧本场景").uncheck();
  // Drift only this disposable installed board. Old production remains readable.
  const board = retained.stages.find((stage: { head: { stage: string } }) => stage.head.stage === "storyboard");
  await json(request.patch(`${root}/stages/storyboard`, { data: { expectedRevision: board.head.revision, payload: { ...board.payload, shots: board.payload.shots.map((shot: { id: string; title: string }) => shot.id === exact.shotId ? { ...shot, title: `${shot.title} revised` } : shot) } } }));
  await page.reload();
  await page.locator('[data-creator-node="opening"] .creator-node-select').click();
  await page.getByRole("tab", { name: "制作", exact: true }).click();
  await expect(production.locator(`[data-production-shot="${exact.shotId}"]`)).toContainText("镜头版本不同");
  await expect(production.locator(`[data-production-shot="${exact.shotId}"]`).getByRole("button", { name: "镜头审核与媒体", exact: true })).toBeDisabled();
  expect((await json(request.get(`${root}/production-bridge`))).proposal).toEqual(bridge.proposal);
  expect((await json(request.get(`${root}/runs`))).runs).toEqual([]);
  expect(errors).toEqual([]);
});
