import { expect, checkedStaticTest as test } from "./fixture";
import { createCreatorGraph } from "./fixtures/creator-graph";
import { json } from "./f5a-fixture";

test("native text stays literal and structural preview Escape writes nothing", async ({ page, request, workbench }, info) => {
  await page.setViewportSize({ width: 1280, height: 768 });
  const id = await createCreatorGraph(request, workbench.apiOrigin, "literal-text");
  const endpoint = `${workbench.apiOrigin}/api/v2/projects/${id}`;
  const read = () => json(request.get(`${endpoint}/graph-workbench`));
  await page.goto(`${workbench.frontendOrigin}/v2/?project=${id}&stage=creator`);
  const before = await read();
  const node = page.locator('[data-creator-node="opening"]');
  const title = '中文  空格 <b>原文 & "引号"</b>';
  const summary = '<img src=x onerror="window.__graphTextExecuted=true">  保留原样';
  const inspector = page.getByRole("complementary", { name: "当前节点详情" });
  await inspector.getByRole("textbox", { name: "章节标题", exact: true }).fill("");
  await inspector.getByRole("textbox", { name: "剧情摘要", exact: true }).fill("");
  await expect(node).toContainText("待填写标题");
  await expect(node).toContainText("待填写剧情");
  await page.screenshot({ path: info.outputPath("blank-viewport.png") });
  await inspector.getByRole("textbox", { name: "章节标题", exact: true }).fill(title);
  await inspector.getByRole("textbox", { name: "剧情摘要", exact: true }).fill(summary);
  await expect(node.locator("strong")).toHaveText(title);
  await expect(node.locator("small")).toHaveText(summary);
  await expect(node.locator("img,b")).toHaveCount(0);
  expect(await page.evaluate(() => (window as any).__graphTextExecuted)).toBeUndefined();
  await page.getByRole("button", { name: "保存图草稿", exact: true }).click();
  const saved = await read();
  expect(saved.draft.payload.mapping.topology).toEqual(before.draft.payload.mapping.topology);
  expect(saved.draft.payload.mapping.sections[0]).toMatchObject({ title, summary });
  await page.screenshot({ path: info.outputPath("literal-viewport.png") });
  const add = page.getByRole("button", { name: "向第 3 行添加节点", exact: true });
  await add.focus(); await page.keyboard.press("Enter");
  await page.getByRole("button", { name: "准备修改预览", exact: true }).click();
  const preview = page.getByRole("dialog", { name: "确认结构修改" });
  await expect(preview).toBeVisible();
  const acknowledged = await read();
  let writes = 0;
  page.on("request", request => { if (new URL(request.url()).pathname.startsWith(`/api/v2/projects/${id}/`) && !["GET", "HEAD"].includes(request.method())) writes++; });
  await page.keyboard.press("Escape");
  await expect(preview).toHaveCount(0);
  expect(await read()).toEqual(acknowledged);
  expect(writes).toBe(0);
  expect((await json(request.get(`${endpoint}/runs`))).runs).toEqual([]);
});
