import { expect, test, type Workbench } from "./fixture";
import { demoProject } from "../src/demo";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { APIRequestContext, Locator, Page } from "@playwright/test";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const still = path.join(root, "docs/verification/supporting/p0-generated/01-arrival.png");

async function ingestAndSelectOfflineCandidate(page: Page, panel: Locator, projectId: string): Promise<string> {
  // The production H3 catalog rejects the 16:9 reviewed still until the
  // author explicitly chooses its documented contain-pad preparation.
  const allowLetterbox = panel.getByLabel("允许黑边画布（保留当前横幅构图）");
  if (!await allowLetterbox.isChecked()) await allowLetterbox.check();
  await panel.getByRole("button", { name: "生成另一候选（冻结当前审核关键帧）" }).click();
  await panel.getByRole("button", { name: "提交一次" }).click();
  const reconcilePost = page.waitForResponse((response) => {
    const pathname = new URL(response.url()).pathname;
    return response.request().method() === "POST"
      && pathname.startsWith(`/api/v2/projects/${projectId}/video-jobs/`)
      && pathname.endsWith("/reconcile");
  });
  await panel.getByRole("button", { name: "获取结果" }).click();
  const reconciledResponse = await reconcilePost;
  expect(reconciledResponse.ok()).toBeTruthy();
  const reconciled = await reconciledResponse.json() as {
    id: string; state: string; error: string | null;
    observed: { videoCodec: string; audioCodec: string | null } | null;
  };
  expect(reconciled).toMatchObject({
    state: "ingested", error: null,
    observed: { videoCodec: "h264", audioCodec: "aac" },
  });
  await panel.getByRole("button", { name: "选择此候选" }).click();
  return reconciled.id;
}

type SelectedPair = {
  projectId: string;
  firstJobId: string;
  secondJobId: string;
  firstSource: string;
  secondSource: string;
};

async function prepareSelectedPair(
  page: Page,
  request: APIRequestContext,
  workbench: Workbench,
): Promise<SelectedPair> {
  const created = await request.post(`${workbench.apiOrigin}/api/v2/projects`, { data: { brief: demoProject.brief, initialStages: [
    { stage: "story_bible", payload: demoProject.storyBible }, { stage: "story_graph", payload: demoProject.storyGraph },
    { stage: "scene_beats", payload: demoProject.sceneBeats }, { stage: "storyboard", payload: demoProject.storyboard },
  ] } });
  expect(created.ok()).toBeTruthy();
  const projectId = (await created.json()).id as string;
  await page.goto(`${workbench.frontendOrigin}/v2/?project=${projectId}&stage=storyboard`);
  await page.getByLabel("审核人标签").fill("P2 H3 browser reviewer");
  await page.getByRole("button", { name: "批准当前分镜" }).click();
  await page.getByLabel("来源声明").fill("P2 local fake fixture");
  await page.getByTestId("managed-image-upload").setInputFiles(still);
  await page.getByRole("button", { name: "保留此候选" }).click();
  await page.getByTestId("visual-intent-source-refs").fill("P2 fixture source");
  await page.getByTestId("save-visual-intent").click();
  await page.getByLabel("审核兼容性说明").fill("Current approved first shot keyframe.");
  const selectionPost = page.waitForResponse((response) => (
    response.request().method() === "POST"
    && new URL(response.url()).pathname === `/api/v2/projects/${projectId}/reviewed-keyframes`
  ));
  await page.getByTestId("select-reviewed-keyframe").click();
  const selectedResponse = await selectionPost;
  expect(selectedResponse.ok()).toBeTruthy();
  const selected = await selectedResponse.json() as { assetId: string };
  // P2 freezes every visible character's explicit reference decision even
  // when the selected keyframe was imported rather than generated by P1.5.
  const workbenchState = await request.get(`${workbench.apiOrigin}/api/v2/projects/${projectId}/visual-workbench`);
  expect(workbenchState.ok()).toBeTruthy();
  const visual = await workbenchState.json() as { characterReferences: { states: Array<{ characterId: string; revision: number }> } };
  const characterId = demoProject.storyboard.shots[0].characterIds[0];
  const referenceState = visual.characterReferences.states.find((state) => state.characterId === characterId);
  const reference = await request.post(`${workbench.apiOrigin}/api/v2/projects/${projectId}/character-references`, { data: {
    characterId, authority: "story_bible", primaryAssetId: selected.assetId, complementaryAssetIds: [],
    expectedReferenceRevision: referenceState?.revision ?? 0, reviewer: "P2 H3 browser reviewer",
    notes: "Explicit fixture reference for the visible character.",
  } });
  expect(reference.ok()).toBeTruthy();
  const panel = page.getByTestId("video-pilot-panel");
  const firstJobId = await ingestAndSelectOfflineCandidate(page, panel, projectId);

  // The adjoining fixture follows the same authored review/selection path.
  // It reuses the explicitly retained local still; the distinct candidate is
  // the separately ingested, reviewed video job for the adjoining shot.
  await page.getByLabel("编辑镜头 双键升起").click();
  await expect(panel.getByText("仅显示当前镜头：双键升起（shot_03）")).toBeVisible();
  await page.getByLabel("审核兼容性说明").fill("Current approved adjoining shot keyframe.");
  await page.getByTestId("select-reviewed-keyframe").click();
  const secondJobId = await ingestAndSelectOfflineCandidate(page, panel, projectId);

  // An explicit route is required before the selected-path player appears;
  // its missing-clip status must remain visible rather than implying a full
  // stitched playthrough.
  await page.getByLabel("路径过滤").selectOption({ index: 1 });
  const firstSource = await page.getByTestId(`video-sequence-job-${firstJobId}`).getAttribute("src");
  expect(firstSource).toContain(`/video-jobs/${firstJobId}/media`);
  return {
    projectId,
    firstJobId,
    secondJobId,
    firstSource: firstSource!,
    secondSource: `${workbench.apiOrigin}/api/v2/projects/${projectId}/video-jobs/${secondJobId}/media`,
  };
}

test("P2 H3 selected pair plays in order with a native final hold", async ({ page, request, workbench }) => {
  const selected = await prepareSelectedPair(page, request, workbench);

  const sequence = page.getByTestId("video-sequence-player");
  // Step 5 shares this production FastAPI page and must surface its separate
  // structural session without pretending the retained two-clip route is a
  // complete branching story.
  await expect(page.getByTestId("branching-video-preview")).toBeVisible();
  await expect(page.getByTestId("branching-missing-media")).toBeVisible();
  const firstSequencePlayer = page.getByTestId(`video-sequence-job-${selected.firstJobId}`);
  const secondSequencePlayer = page.getByTestId(`video-sequence-job-${selected.secondJobId}`);
  await expect(firstSequencePlayer).toBeVisible();
  await expect(page.getByTestId("video-route-sequence-status")).toContainText("路径尚不完整");

  // This is an actual native playback/ended transition of the downloaded MP4,
  // rather than a synthetic event. The second source must then begin playing.
  await sequence.getByRole("button", { name: "播放当前" }).click();
  await expect.poll(() => firstSequencePlayer.evaluate((video) => (video as HTMLVideoElement).currentTime)).toBeGreaterThan(0);
  await expect(secondSequencePlayer).toBeVisible({ timeout: 9_000 });
  expect(await secondSequencePlayer.getAttribute("src")).toBe(`/api/v2/projects/${selected.projectId}/video-jobs/${selected.secondJobId}/media`);
  await expect.poll(() => secondSequencePlayer.evaluate((video) => (video as HTMLVideoElement).currentTime)).toBeGreaterThan(0);

  await sequence.getByRole("button", { name: "上一镜头" }).click();
  await expect(firstSequencePlayer).toBeVisible();
  await sequence.getByRole("button", { name: "下一镜头" }).click();
  await expect(secondSequencePlayer).toBeVisible();
  await secondSequencePlayer.evaluate((video) => { (video as HTMLVideoElement).currentTime = 0.25; });
  await expect.poll(() => secondSequencePlayer.evaluate((video) => (video as HTMLVideoElement).currentTime)).toBeGreaterThan(0.2);
  const restartReset = secondSequencePlayer.evaluate((video) => new Promise<boolean>((resolve) => {
    const native = video as HTMLVideoElement;
    const beforeRestart = native.currentTime;
    const onSeeking = () => {
      if (native.currentTime < beforeRestart) {
        native.removeEventListener("seeking", onSeeking);
        resolve(true);
      }
    };
    native.addEventListener("seeking", onSeeking);
    window.setTimeout(() => { native.removeEventListener("seeking", onSeeking); resolve(false); }, 1_000);
  }));
  await sequence.getByRole("button", { name: "重启当前" }).click();
  expect(await restartReset).toBeTruthy();
  await expect.poll(() => secondSequencePlayer.evaluate((video) => !(video as HTMLVideoElement).paused)).toBeTruthy();
  // The final hold is also native: wait for the actual downloaded H3 clip to
  // end instead of manufacturing an `ended` event in the browser.
  await expect.poll(
    () => secondSequencePlayer.evaluate((video) => (video as HTMLVideoElement).ended),
    { timeout: 9_000 },
  ).toBeTruthy();
  await expect(secondSequencePlayer).toBeVisible();
});

test("P2 H3 selected pair persists selected IDs and bytes through file-SQLite restart", async ({ page, request, workbench }) => {
  const selected = await prepareSelectedPair(page, request, workbench);
  const firstBytes = await request.get(`${workbench.apiOrigin}${selected.firstSource}`, { headers: { Range: "bytes=0-15" } });
  expect(firstBytes.status()).toBe(206);

  // Restart persistence is deliberately separate from native playback: both
  // contracts are meaningful, but their combined browser setup exceeded the
  // per-test budget despite the backend being healthy.
  await workbench.restartBackend();
  await page.reload();
  await page.getByLabel("路径过滤").selectOption({ index: 1 });
  await expect(page.getByTestId(`video-sequence-job-${selected.firstJobId}`)).toBeVisible();
  const persisted = await request.get(`${workbench.apiOrigin}/api/v2/projects/${selected.projectId}/video-jobs`);
  expect(persisted.ok()).toBeTruthy();
  const selectedJobs = ((await persisted.json()) as { jobs: Array<{ id: string; selected: boolean }> }).jobs
    .filter((job) => job.selected).map((job) => job.id).sort();
  expect(selectedJobs).toEqual([selected.firstJobId, selected.secondJobId].sort());
  const afterFirstBytes = await request.get(`${workbench.apiOrigin}${selected.firstSource}`, { headers: { Range: "bytes=0-15" } });
  const afterSecondBytes = await request.get(selected.secondSource, { headers: { Range: "bytes=0-15" } });
  expect(afterFirstBytes.status()).toBe(206);
  expect(afterSecondBytes.status()).toBe(206);
  expect(await afterFirstBytes.body()).toEqual(await firstBytes.body());
});
