import { expect, test, type Workbench } from "./fixture";
import { demoProject } from "../src/demo";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { APIRequestContext, Locator, Page } from "@playwright/test";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const still = path.join(root, "docs/verification/supporting/p0-generated/01-arrival.png");

async function ingestAndSelectOfflineCandidate(page: Page, panel: Locator, projectId: string, inFrame: number): Promise<string> {
  // The production H3 catalog rejects the 16:9 reviewed still until the
  // author explicitly chooses its documented contain-pad preparation.
  const allowLetterbox = panel.getByLabel("允许黑边画布（保留当前横幅构图）");
  if (!await allowLetterbox.isChecked()) await allowLetterbox.check();
  await panel.getByLabel("H3 时长（已审核）").selectOption("8");
  await panel.getByRole("button", { name: "生成另一候选（冻结当前审核关键帧）" }).click();
  await panel.getByRole("button", { name: "提交一次" }).click();
  const reconcilePost = page.waitForResponse((response) => {
    const pathname = new URL(response.url()).pathname;
    return response.request().method() === "POST"
      && pathname.startsWith(`/api/v2/projects/${projectId}/video-jobs/`)
      && pathname.endsWith("/reconcile");
  });
  await panel.getByRole("button", { name: "获取结果" }).click();
  const reconciledResponse = await reconcilePost;
  expect(reconciledResponse.ok()).toBeTruthy();
  const reconciled = await reconciledResponse.json() as {
    id: string; state: string; error: string | null;
    observed: { videoCodec: string; audioCodec: string | null } | null;
  };
  expect(reconciled).toMatchObject({
    state: "ingested", error: null,
    observed: { videoCodec: "h264", audioCodec: "aac" },
  });
  const review = panel.getByTestId(`video-segment-review-${reconciled.id}`);
  await review.getByLabel("片段入点（帧）").fill(String(inFrame));
  await review.getByRole("button", { name: "准备此连续片段（不选择）" }).click();
  const preview = review.locator('video[data-testid^="video-segment-preview-"]');
  await expect(preview).toBeVisible();
  await expect.poll(() => preview.evaluate((video) => (video as HTMLVideoElement).duration)).toBeGreaterThan(0);
  await review.getByLabel("选择人").fill("P2 H3 browser reviewer");
  await review.getByLabel("片段审核说明").fill("Synthetic fixture: explicit derivative preview and selection.");
  await review.getByRole("button", { name: "确认选择此播放片段" }).click();
  await expect(review.getByText("当前已明确选择", { exact: false })).toBeVisible();
  return reconciled.id;
}

type SelectedPair = {
  projectId: string;
  firstJobId: string;
  secondJobId: string;
  firstSource: string;
  secondSource: string;
};

async function prepareSelectedPair(
  page: Page,
  request: APIRequestContext,
  workbench: Workbench,
): Promise<SelectedPair> {
  const created = await request.post(`${workbench.apiOrigin}/api/v2/projects`, { data: { brief: demoProject.brief, initialStages: [
    { stage: "story_bible", payload: demoProject.storyBible }, { stage: "story_graph", payload: demoProject.storyGraph },
    { stage: "scene_beats", payload: demoProject.sceneBeats }, { stage: "storyboard", payload: demoProject.storyboard },
  ] } });
  expect(created.ok()).toBeTruthy();
  const projectId = (await created.json()).id as string;
  await page.goto(`${workbench.frontendOrigin}/v2/?project=${projectId}&stage=storyboard`);
  await page.getByLabel("审核人标签").fill("P2 H3 browser reviewer");
  await page.getByRole("button", { name: "批准当前分镜" }).click();
  await page.getByLabel("来源声明").fill("P2 local fake fixture");
  await page.getByTestId("managed-image-upload").setInputFiles(still);
  await page.getByRole("button", { name: "保留此候选" }).click();
  await page.getByTestId("visual-intent-source-refs").fill("P2 fixture source");
  await page.getByTestId("save-visual-intent").click();
  await page.getByLabel("审核兼容性说明").fill("Current approved first shot keyframe.");
  const selectionPost = page.waitForResponse((response) => (
    response.request().method() === "POST"
    && new URL(response.url()).pathname === `/api/v2/projects/${projectId}/reviewed-keyframes`
  ));
  await page.getByTestId("select-reviewed-keyframe").click();
  const selectedResponse = await selectionPost;
  expect(selectedResponse.ok()).toBeTruthy();
  const selected = await selectedResponse.json() as { assetId: string };
  // P2 freezes every visible character's explicit reference decision even
  // when the selected keyframe was imported rather than generated by P1.5.
  const workbenchState = await request.get(`${workbench.apiOrigin}/api/v2/projects/${projectId}/visual-workbench`);
  expect(workbenchState.ok()).toBeTruthy();
  const visual = await workbenchState.json() as { characterReferences: { states: Array<{ characterId: string; revision: number }> } };
  const characterId = demoProject.storyboard.shots[0].characterIds[0];
  const referenceState = visual.characterReferences.states.find((state) => state.characterId === characterId);
  const reference = await request.post(`${workbench.apiOrigin}/api/v2/projects/${projectId}/character-references`, { data: {
    characterId, authority: "story_bible", primaryAssetId: selected.assetId, complementaryAssetIds: [],
    expectedReferenceRevision: referenceState?.revision ?? 0, reviewer: "P2 H3 browser reviewer",
    notes: "Explicit fixture reference for the visible character.",
  } });
  expect(reference.ok()).toBeTruthy();
  const panel = page.getByTestId("video-pilot-panel");
  const firstJobId = await ingestAndSelectOfflineCandidate(page, panel, projectId, 24);

  // The adjoining fixture follows the same authored review/selection path.
  // It reuses the explicitly retained local still; the distinct candidate is
  // the separately ingested, reviewed video job for the adjoining shot.
  await page.getByLabel("编辑镜头 双键升起").click();
  await expect(panel.getByText("仅显示当前镜头：双键升起（shot_03）")).toBeVisible();
  await page.getByLabel("审核兼容性说明").fill("Current approved adjoining shot keyframe.");
  await page.getByTestId("select-reviewed-keyframe").click();
  const secondJobId = await ingestAndSelectOfflineCandidate(page, panel, projectId, 0);

  // An explicit route is required before the selected-path player appears;
  // its missing-clip status must remain visible rather than implying a full
  // stitched playthrough.
  await page.getByLabel("路径过滤").selectOption({ index: 1 });
  await expect(page.getByTestId("video-route-sequence-status")).toContainText("路径尚不完整");
  await expect(page.getByTestId("video-sequence-player")).toHaveCount(0);
  const firstSource = `/api/v2/projects/${projectId}/video-jobs/${firstJobId}/playback`;
  return {
    projectId,
    firstJobId,
    secondJobId,
    firstSource: firstSource!,
    secondSource: `${workbench.apiOrigin}/api/v2/projects/${projectId}/video-jobs/${secondJobId}/playback`,
  };
}

test("P2 H3 selected segments are exact and partial routes do not play", async ({ page, request, workbench }) => {
  const selected = await prepareSelectedPair(page, request, workbench);
  await expect(page.getByTestId("branching-video-preview")).toBeVisible();
  await expect(page.getByTestId("branching-missing-media")).toBeVisible();
  await expect(page.getByTestId("video-sequence-player")).toHaveCount(0);
  const jobsResponse = await request.get(`${workbench.apiOrigin}/api/v2/projects/${selected.projectId}/video-jobs`);
  const jobs = (await jobsResponse.json() as { jobs: Array<{ id: string; playbackSegment?: { inFrame: number; outFrame: number; selected: boolean } }> }).jobs;
  expect(jobs.find((job) => job.id === selected.firstJobId)?.playbackSegment).toMatchObject({ inFrame: 24, outFrame: 168, selected: true });
  expect(jobs.find((job) => job.id === selected.secondJobId)?.playbackSegment).toMatchObject({ inFrame: 0, outFrame: 192, selected: true });
  expect((await request.get(`${workbench.apiOrigin}${selected.firstSource}`, { headers: { Range: "bytes=0-15" } })).status()).toBe(206);
});

test("P2 H3 selected pair persists selected IDs and bytes through file-SQLite restart", async ({ page, request, workbench }) => {
  const selected = await prepareSelectedPair(page, request, workbench);
  const firstBytes = await request.get(`${workbench.apiOrigin}${selected.firstSource}`, { headers: { Range: "bytes=0-15" } });
  expect(firstBytes.status()).toBe(206);

  // Restart persistence is deliberately separate from native playback: both
  // contracts are meaningful, but their combined browser setup exceeded the
  // per-test budget despite the backend being healthy.
  await workbench.restartBackend();
  await page.reload();
  await page.getByLabel("路径过滤").selectOption({ index: 1 });
  await expect(page.getByTestId("video-sequence-player")).toHaveCount(0);
  const persisted = await request.get(`${workbench.apiOrigin}/api/v2/projects/${selected.projectId}/video-jobs`);
  expect(persisted.ok()).toBeTruthy();
  const selectedJobs = ((await persisted.json()) as { jobs: Array<{ id: string; playbackSegment?: { selected: boolean } }> }).jobs
    .filter((job) => job.playbackSegment?.selected).map((job) => job.id).sort();
  expect(selectedJobs).toEqual([selected.firstJobId, selected.secondJobId].sort());
  const afterFirstBytes = await request.get(`${workbench.apiOrigin}${selected.firstSource}`, { headers: { Range: "bytes=0-15" } });
  const afterSecondBytes = await request.get(selected.secondSource, { headers: { Range: "bytes=0-15" } });
  expect(afterFirstBytes.status()).toBe(206);
  expect(afterSecondBytes.status()).toBe(206);
  expect(await afterFirstBytes.body()).toEqual(await firstBytes.body());
});
